### ISSUE TITLE
Datapack Characters appearing when they (probably) shouldnt

### ISSUE THREAD

**Issue by Bjorn0411** [Alexofp/BDCC#103] opened 2024-08-08 22:32 UTC
So I've got a character, in this case Bremen, for my datapack where I've ticked "Exclude from encounters" (aswell as disable forget and disable meet) but people are still able to encounter him, so far I've had reports from other players of:

 - [ ] excluded character shows up at the stocks
 - [ ] excluded character shows up at the exhibitionist "reveal x body part" encounter
 - [ ] excluded character shows up at the "attack, submit, pay 5 credits" encounter
 
The first two sound like a simple oversight, last one I can only assume is a bug of some kind. Last two reported by Zyro on the mods-discussion channel on discord, at around midnight between the 8th and 9th.
edit: I think he was using "look for trouble" and not moving, if that makes any difference.

---
Also, quick bonus suggestion:

 - [ ] disabling both meeting and forgetting a character, should either automatically, or optionally by the pack creator, hide them from the character list in the encounters menu.

this is useful for me in particular as I've got a scene of someone sitting on the ground, by themselves, which I achieve by using a invisible hidden character in the cuddle scene. It'd be nice if my "DEBUG" character wasnt visible in the npc character list ^^

(edit: someone on the discord pointed out a vanilla ""npc"" called playerstash also has no visual data so I can get rid of my debug character anyways, but I think this feature would still be quite useful! Lets me for example hide a cheeky duplicate character trick I use elsewhere for modified looks)

**Comment by Zyrro** [comment] 2024-08-12 04:26
I was able to get encounters from datapack characters flagged as "Exclude from Encounters" using Look for Trouble, and by Moving around, both work and are reproducible.

The random encounters I was able to get using both Walking around and Looking For Trouble with Dynamic NPCs Flagged as "Exclude from Encounters" are the following encounters: EngineerCaughtOffLimitsScene, NurseCaughtOffLimitsScene, GuardOfflimitsCanSlipByScene, GuardCaughtOfflimitsScene, InmateExposureFlashScene, InmateExposureForcedSexScene, InmateExposureFlashScene, StocksWillingDynNpcScene, StocksUnwillingDynNpcScene

They'll also show up for the slutwall encounters

The only encounter I was unable to get was the InmateExposureProstitutionEvent, and this has nothing to do with the "Exclude from Encounters" tag, but rather because Datapack NPCs don't have an "InmateType" defined, and since only Dynamic NPCs with the SexDeviant Tag can be selected for that event, you can never see this event with a datapack dynamic NPC. (The lack of InmateType tag in the datapack editor is probably an oversight considering that the only time InmateType actually matters for NPCs outside of generating their inventory is specifically InmateExposureProstitutionEvent)

As far as I can tell; the variable "excludeEncounters" that is set in the datapack creator isn't referenced in anywhere that determines what NPCs to select for an encounter.

**Comment by CanInBad** [comment] 2024-09-18 08:46
probably fixed in https://github.com/Alexofp/BDCC/commit/4bdc1ff27366f0f4218264ba0b095036ba9f367f

**Comment by Alexofp** [comment] 2024-09-18 08:47
probably yeah x3

**Closed** 2024-12-17 13:58 UTC
